### ISSUE TITLE
Input files - adapter trimmed or not?

### ISSUE THREAD

**Issue by iahdb** [JordyCoolen/easyseq_covid19#4]
Hi, 

Just wondering if the fastq files need to be adapter trimmed first before inputting into the pipeline?

**Comment by JordyCoolen** [comment]
Hi,

The pipeline is able to use data produced using the EasySeq kit directly after obtaining the demultiplexed data from the Illumina machines.
The pipeline uses fastp for removing adapter, removing artifacts etc. for you.
So no need to preprocess your data.

Hope this helps you.

Best,

Jordy

**Comment by iahdb** [comment]
Yes thank you that helps!
