### ISSUE TITLE
updated conda environments download

### ISSUE THREAD

**Issue by iahdb** [JordyCoolen/easyseq_covid19#5]
Is it possible to provide a link that would work with wget for downloading the conda.tar.gz update?

using wget with the current download link just downloads a file called "download" which then can't be extracted as it doesn't have a .tar.gz extension. This would make it simpler to get onto a remote server. 

Thanks!

**Comment by JordyCoolen** [comment]
The following link should work with wget:

https://surfdrive.surf.nl/files/index.php/s/ggoLXzMoa5iSZYa/download

P.s. also don't forget that the pangolin version in this download is far from being the recent version.
Because of constant updates on the pangolin side, you have to update it manually yourself.

**Comment by iahdb** [comment]
Unfortunately, that link with wget just downloads an unreadable file called "download" to my server. 
Clicking the link works fine for downloading to my local computer and it downloads correctly as conda.tar.gz but it doesn't do the same with wget on my remote server.
I could just rsync from my local to remote server but that's having issues as well (for a separate reason, possibly to do with my Institute's VPN).

No worries about Pangolin, I keep it updated for use with ARTIC workflows too, I'll make sure to check it.

**Comment by JordyCoolen** [comment]
the file that you download called "download" you can just rename it to conda.tar.gz
and then extract the contact of the conda.tar.gz with:

tar -xzvf conda.tar.gz

I just tested it and this works fine.

**Comment by JordyCoolen** [comment]
contact = content

**Comment by JordyCoolen** [comment]
You were able to get everything to work?

**Comment by iahdb** [comment]
Hi Jordy, 

Apologies for the delay. In the end, the sequencing service I used ran it through their own pipeline so I haven't tried yours again yet.

**Comment by JordyCoolen** [comment]
No problem, as long as you are able to obtain your results.
Kind regards
